apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-develop-deployment
  namespace: kubernetes-cluster-gaganjotsingh02
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gaganshera/i-gaganjotsingh02-develop:latest
          ports:
            - name: http
              containerPort: 3010
              protocol: TCP
          # envFrom:
          # - configMapRef:
          #     name: app-settings
          # - secretRef:
          #     name: secret-info
          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-develop
  namespace: kubernetes-cluster-gaganjotsingh02
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 3010
      targetPort: 3010